name: birddlc
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11

  # Core scientific stack
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pillow
  - pyyaml
  - scikit-image
  - opencv

  # Deep learning
  - pytorch
  - torchvision
  - cpuonly
  # - pytorch-cuda=12.1   # Remove this line if using CPU only

  # pip packages
  - pip
  - pip:
      - deeplabcut

  # conda env create -f environment.yml
  # conda activate birddlc